.TH aeolus-cli 1  "July 07, 2011" "version 0.4" "USER COMMANDS"
.SH NAME
aeolus-cli push \- command for pushing aeolus images to back end providers
.SH SYNOPSIS
.B aeolus-cli push [\-h|--help] [\-I|--image [image-id]] [\-B|--build [build-id]] [-m|--targetimage]] [-A|--account[account-name]]
.SH DESCRIPTION
aeolus-cli push allows users to push target images to particular backend providers.
.SH OPTIONS
.TP
\-I|--image <id>
The image id for pushing all target images associated with this image
.TP
\-B|--build <id>
The build id for pushing all target images associated with this build
.TP
\-m|--targetimage <id>
The id of the target image to push
.TP
\-A|--account <id>
A comma separated list of account that the target images should be pushed to
.TP
Get usage information for this command and associated commmands
\-h, --help
.SH EXAMPLES
.TP
Push target images associated with an image to each of specified accounts
.B aeolus-cli push
\--image 12345678-bbbb-1234--1234567890ab
\--account ec2-account,rhevm-account
.TP
Push target images associated with a build to each of the specified accounts
.B aeolus-cli push
\--build 12345678-bbbb-1234--1234567890ab
\--account ec2-account,rhevm-account
.TP
Push a target image to each of the specified accounts
.B aeolus-cli push
\--targetimage 12345678-bbbb-1234--1234567890ab
\--account ec2-account,ec2-account2
.SH AUTHOR
Martyn Taylor (mtaylor@redhat.com), Jason Guiditta (jguiditta@redhat.com)
.SH SEE ALSO
aeolus-cli-list(1), aeolus-cli-build(1), aeolus-cli-import(1), aeolus-cli-status(1)
